// Code generated by goctl. DO NOT EDIT!
// Source: project.proto

package server

import (
	"context"

	"github.com/maniizu3110/attendance/rpc/project/internal/logic"
	"github.com/maniizu3110/attendance/rpc/project/internal/svc"
	"github.com/maniizu3110/attendance/rpc/project/proto/add"
)

type ProjectServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedProjectServer
}

func NewProjectServer(svcCtx *svc.ServiceContext) *ProjectServer {
	return &ProjectServer{
		svcCtx: svcCtx,
	}
}

func (s *ProjectServer) Add(ctx context.Context, in *add.AddReq) (*add.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
