// Code generated by goctl. DO NOT EDIT!
// Source: server.proto

package server

import (
	"context"

	"github.com/maniizu3110/attendance/rpc/attendance/internal/logic"
	"github.com/maniizu3110/attendance/rpc/attendance/internal/svc"
	"github.com/maniizu3110/attendance/rpc/attendance/proto/add"
	)

type AdderServer struct {
	svcCtx *svc.ServiceContext
	add.UnimplementedAdderServer
}

func NewAdderServer(svcCtx *svc.ServiceContext) *AdderServer {
	return &AdderServer{
		svcCtx: svcCtx,
	}
}

func (s *AdderServer) Add(ctx context.Context, in *add.AddReq) (*add.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
