// Code generated by goctl. DO NOT EDIT!
// Source: project.proto

package project

import (
	"context"

	"github.com/maniizu3110/attendance/rpc/project/proto/add"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddReq  = add.AddReq
	AddResp = add.AddResp

	Project interface {
		Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error)
	}

	defaultProject struct {
		cli zrpc.Client
	}
)

func NewProject(cli zrpc.Client) Project {
	return &defaultProject{
		cli: cli,
	}
}

func (m *defaultProject) Add(ctx context.Context, in *AddReq, opts ...grpc.CallOption) (*AddResp, error) {
	client := add.NewProjectClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
